### ISSUE TITLE
An error occurred while trying to run simulation via sumo-gui

### ISSUE THREAD

**Issue by juanwulu** [MrLeedom/sumo_RL#2]
Hello there,
       while I was trying to run your code via sumo-gui, an error occurred with the following statement.

> Error: An unknown lane ('') was tried to be set as incoming to junction 'center'.
> Error: Unknown from-node 'center' for edge '-gneE0'.

Is there anything to do with the network building?

**Comment by DiyaMoon** [comment]
我也有这个问题，请问你解决了吗？

**Comment by 123yumu** [comment]
> 

在netedit保存一下路网文件

**Comment by 123yumu** [comment]
> 我也有这个问题，请问你解决了吗？

在netedit保存一下路网文件
